### ISSUE TITLE
RailCraft incompatibility

### ISSUE THREAD

**Issue by NathanPB** [Azanor/thaumcraft-5#678]
Hello. Im trying to start Thaumcraft-1.10.2-6.0.BETA6 and Railcraft_1.10.2-10.3.1 but i got the following crash: https://paste.ee/p/6WUt0

I don't know exactly what it is, but I think I should report

**Comment by liach** [comment]
@azanor you should not assume that conversions are not lambdas

**Comment by NathanPB** [comment]
I fixed it downgrading RailCraft to Railcraft_1.10.2-10.2.0

**Comment by liach** [comment]
@NathanPB Because Railcraft adds new potion in the new version. Tc is still not going to work with some of the potion mods.

**Comment by MainFreak** [comment]
This has been fixed for a while now in the new beta. But please report any further issues [here](https://github.com/Azanor/thaumcraft-beta/issues)

**Comment by liach** [comment]
just close this one.

**Comment by MainFreak** [comment]
It technically is not my job to run around telling people where to report stuff, so I am also not authorized to just close issues ;p
@Azanor you may want to clean up the issues of this repository.
